# How to create continuation that throw errors

